# @package _global_

hydra:
  job:
    config:
      override_dirname:
        kv_sep: ':'
        item_sep: '__'
        exclude_keys:
          - run_config
          - distributed_training.distributed_port
          - task.data
          - model.w2v_path
          - checkpoint.restore_file
  sweep:
    dir: /checkpoint/${env:USER}/wav2vec/${env:PREFIX}/${hydra.job.config_name}_${hydra.launcher.gpus_per_node}/${hydra.job.override_dirname}
    subdir: ${hydra.job.config_name}/${hydra.job.override_dirname}
  launcher:
    cpus_per_task: 80
    gpus_per_node: 8
    tasks_per_node: 1
    nodes: 1
    partition: devlab,learnlab
    mem_gb: 400
    timeout_min: 4320
    max_num_timeout: 10
    constraint: volta32gb
    name: ${env:PREFIX}_${hydra.job.config_name}_${hydra.job.override_dirname}
    submitit_folder: ${hydra.sweep.dir}/submitit/%j
    exclude: learnfair1381,learnfair5192,learnfair2304,learnfair5301,learnfair5208

distributed_training:
  # ddp_backend: no_c10d
  distributed_port: -1
